language: node_js

node_js:
  - 'node'

install:
  - "npm install"

cache:
  directories:
    - "./node_modules"

script:
  - "npm run build"

before_deploy:
  - "npm install -g firebase-tools"

deploy:
  - provider: script
    script:
      - firebase deploy --token "$FIREBASE_TOKEN"
    skip_cleanup: true
    on:
      branch: master


notifications:
  email: false
